import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ClientLoader from "@/components/load/loader";


export const metadata: Metadata = {
  title: "Team PangPang15",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="ko" className="h-full">
      <body
        className={`
          antialiased
          bg-white text-gray-900
          dark:bg-[#1C1917] dark:text-white
          h-full
        `}
      >
        <ClientLoader>
          <div className="flex flex-col min-h-screen">
            <main className="flex-grow w-full max-w-[640px] mx-auto px-4 sm:px-6">
              {children}
            </main>
          </div>
          </ClientLoader>
      </body>
    </html>
  );
}