import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ClerkWrapper from "@/components/etc/clerkwrpper";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PangPang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="overflow-hidden">
      <body className="h-full antialiased">
        <ClerkWrapper>
          <div className="flex flex-col h-full">
            <main className="flex-grow w-full">
              {children}
            </main>
          </div>
        </ClerkWrapper>
      </body>
    </html>
  );
}
